### ISSUE TITLE
AttributeError after upgrading to 1.3

### ISSUE THREAD

**Issue by mpibpc-mroose** [rocioar/flake8-django#117]
After upgrading to 1.3 I get the following error:

```python
root@django:/source# flake8
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flake8/checker.py", line 687, in _run_checks
    return checker.run_checks()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flake8/checker.py", line 597, in run_checks
    self.run_ast_checks()
  File "/usr/local/lib/python3.11/site-packages/flake8/checker.py", line 500, in run_ast_checks
    for (line_number, offset, text, _) in runner:
  File "/usr/local/lib/python3.11/site-packages/flake8_django/checker.py", line 119, in run
    astroid_parser.visit(self.astroid_tree)
  File "/usr/local/lib/python3.11/site-packages/flake8_django/checker.py", line 69, in visit
    self.run_checkers(
  File "/usr/local/lib/python3.11/site-packages/flake8_django/checker.py", line 78, in run_checkers
    checker_issues = checker.run(node)
                     ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flake8_django/checkers/model_form.py", line 53, in run
    if target.name == 'fields' and self.is_string_dunder_all(element):
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flake8_django/checkers/model_form.py", line 33, in is_string_dunder_all
    node_value = element.value.value
                 ^^^^^^^^^^^^^^^^^^^
AttributeError: 'BinOp' object has no attribute 'value'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/usr/local/lib/python3.11/site-packages/flake8/main/application.py", line 375, in run
    self._run(argv)
  File "/usr/local/lib/python3.11/site-packages/flake8/main/application.py", line 364, in _run
    self.run_checks()
  File "/usr/local/lib/python3.11/site-packages/flake8/main/application.py", line 271, in run_checks
    self.file_checker_manager.run()
  File "/usr/local/lib/python3.11/site-packages/flake8/checker.py", line 309, in run
    self.run_parallel()
  File "/usr/local/lib/python3.11/site-packages/flake8/checker.py", line 275, in run_parallel
    for ret in pool_map:
  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 451, in <genexpr>
    return (item for chunk in result for item in chunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 873, in next
    raise value
AttributeError: 'BinOp' object has no attribute 'value'
```

Checking the same code with v1.2 does not raise this error.

**Comment by yalef** [comment]
Hi! I've investigated your issue. This happens in cases when we want to expand `fields` attr in `Meta` class of Form.
For example:
```
class ExtendedUserForm(UserForm):
    class Meta(UserForm):
        fields = UserForm.Meta.fields + ('email',)
```
It will be resolved in #116 PR
