### ISSUE TITLE
Flake8 failed to load plugin "DJ0" due to No module named 'checkers'

### ISSUE THREAD

**Issue by srtab** [rocioar/flake8-django#15]
Hi @rocioar,

Congrats for the great job, it looks a promissor plugin to garante best practices in Django projects.
I'm trying to use it in my projects and i'm getting this traceback:
```python
Traceback (most recent call last):
  File "/app/.tox/lint/lib/python3.6/site-packages/flake8/plugins/manager.py", line 178, in load_plugin
    self._load(verify_requirements)
  File "/app/.tox/lint/lib/python3.6/site-packages/flake8/plugins/manager.py", line 150, in _load
    self._plugin = resolve()
  File "/app/.tox/lint/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/app/.tox/lint/lib/python3.6/site-packages/flake8_django.py", line 3, in <module>
    from checkers import ModelFieldChecker, URLChecker, RenderChecker
ModuleNotFoundError: No module named 'checkers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.tox/lint/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/app/.tox/lint/lib/python3.6/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/app/.tox/lint/lib/python3.6/site-packages/flake8/main/application.py", line 396, in run
    self._run(argv)
  File "/app/.tox/lint/lib/python3.6/site-packages/flake8/main/application.py", line 383, in _run
    self.initialize(argv)
  File "/app/.tox/lint/lib/python3.6/site-packages/flake8/main/application.py", line 365, in initialize
    self.find_plugins()
  File "/app/.tox/lint/lib/python3.6/site-packages/flake8/main/application.py", line 191, in find_plugins
    self.check_plugins.load_plugins()
  File "/app/.tox/lint/lib/python3.6/site-packages/flake8/plugins/manager.py", line 423, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "/app/.tox/lint/lib/python3.6/site-packages/flake8/plugins/manager.py", line 311, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/app/.tox/lint/lib/python3.6/site-packages/flake8/plugins/manager.py", line 421, in load_plugin
    return plugin.load_plugin()
  File "/app/.tox/lint/lib/python3.6/site-packages/flake8/plugins/manager.py", line 186, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "DJ0" due to No module named 'checkers'.
```

I'm using Django 2.1 with python 3.6.

Thanks,
Sandro Rodrigues

**Comment by rocioar** [comment]
@srtab @lithammer fixed the issue, and I also updated the new version to pypi, so a simple `pip install flake8-django` should fix the issue for you now.

**Comment by srtab** [comment]
Thanks for the fast response @rocioar and @lithammer :+1:
