### ISSUE TITLE
Flake8 multiprocessing error after installing flake8-django (maybe Python 2.7 related)

### ISSUE THREAD

**Issue by pydolan** [rocioar/flake8-django#42]
I ran into an error with flake8-django on Python 2.7, where the following error shows up only after installing flake8-django:

```
Traceback (most recent call last):
  File "/Users/dol/.pyenv/versions/eba/bin/flake8", line 10, in <module>
    sys.exit(main())
  File "/Users/dol/.pyenv/versions/2.7.15/envs/eba/lib/python2.7/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/Users/dol/.pyenv/versions/2.7.15/envs/eba/lib/python2.7/site-packages/flake8/main/application.py", line 394, in run
    self._run(argv)
  File "/Users/dol/.pyenv/versions/2.7.15/envs/eba/lib/python2.7/site-packages/flake8/main/application.py", line 382, in _run
    self.run_checks()
  File "/Users/dol/.pyenv/versions/2.7.15/envs/eba/lib/python2.7/site-packages/flake8/main/application.py", line 301, in run_checks
    self.file_checker_manager.run()
  File "/Users/dol/.pyenv/versions/2.7.15/envs/eba/lib/python2.7/site-packages/flake8/checker.py", line 328, in run
    self.run_parallel()
  File "/Users/dol/.pyenv/versions/2.7.15/envs/eba/lib/python2.7/site-packages/flake8/checker.py", line 292, in run_parallel
    for ret in pool_map:
  File "/Users/dol/.pyenv/versions/2.7.15/lib/python2.7/multiprocessing/pool.py", line 289, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/Users/dol/.pyenv/versions/2.7.15/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
AttributeError: 'Name' object has no attribute 'value'
```

I haven't looked into the error much, but notice python 2.7 is not listed in the setup.py file, so wondering if this is related.  Thoughts on how to fix?

**Comment by rocioar** [comment]
We don't support Python 7.
