### ISSUE TITLE
DJ03 crashing flake8 with AttributeError: 'Attribute' object has no attribute 'id'

### ISSUE THREAD

**Issue by jon-mcclung-fortyau** [rocioar/flake8-django#48]
The following code:

```
return render(
    self.request,
    self.template_name,
    self.get_context_data(
        form=form
    ),
)
```

produces the following traceback:
```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/myenv/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/anaconda3/envs/myenv/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/anaconda3/envs/myenv/lib/python3.7/site-packages/flake8/checker.py", line 666, in _run_checks
    return checker.run_checks()
  File "/usr/local/anaconda3/envs/myenv/lib/python3.7/site-packages/flake8/checker.py", line 598, in run_checks
    self.run_ast_checks()
  File "/usr/local/anaconda3/envs/myenv/lib/python3.7/site-packages/flake8/checker.py", line 502, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/usr/local/anaconda3/envs/myenv/lib/python3.7/site-packages/flake8_django/checker.py", line 56, in run
    parser.visit(self.tree)
  File "/usr/local/anaconda3/envs/myenv/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/anaconda3/envs/myenv/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/usr/local/anaconda3/envs/myenv/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/anaconda3/envs/myenv/lib/python3.7/site-packages/flake8_django/checker.py", line 39, in visit_ClassDef
    self.capture_issues_visitor('ClassDef', node)
  File "/usr/local/anaconda3/envs/myenv/lib/python3.7/site-packages/flake8_django/checker.py", line 33, in capture_issues_visitor
    self.generic_visit(node)
  File "/usr/local/anaconda3/envs/myenv/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/usr/local/anaconda3/envs/myenv/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/anaconda3/envs/myenv/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/usr/local/anaconda3/envs/myenv/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/anaconda3/envs/myenv/lib/python3.7/ast.py", line 281, in generic_visit
    self.visit(value)
  File "/usr/local/anaconda3/envs/myenv/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/anaconda3/envs/myenv/lib/python3.7/site-packages/flake8_django/checker.py", line 36, in visit_Call
    self.capture_issues_visitor('Call', node)
  File "/usr/local/anaconda3/envs/myenv/lib/python3.7/site-packages/flake8_django/checker.py", line 30, in capture_issues_visitor
    issues = checker.run(node)
  File "/usr/local/anaconda3/envs/myenv/lib/python3.7/site-packages/flake8_django/checkers/render.py", line 22, in run
    if isinstance(arg, ast.Call) and arg.func.id == 'locals':
AttributeError: 'Attribute' object has no attribute 'id'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/myenv/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/envs/myenv/lib/python3.7/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/usr/local/anaconda3/envs/myenv/lib/python3.7/site-packages/flake8/main/application.py", line 393, in run
    self._run(argv)
  File "/usr/local/anaconda3/envs/myenv/lib/python3.7/site-packages/flake8/main/application.py", line 381, in _run
    self.run_checks()
  File "/usr/local/anaconda3/envs/myenv/lib/python3.7/site-packages/flake8/main/application.py", line 300, in run_checks
    self.file_checker_manager.run()
  File "/usr/local/anaconda3/envs/myenv/lib/python3.7/site-packages/flake8/checker.py", line 329, in run
    self.run_parallel()
  File "/usr/local/anaconda3/envs/myenv/lib/python3.7/site-packages/flake8/checker.py", line 293, in run_parallel
    for ret in pool_map:
  File "/usr/local/anaconda3/envs/myenv/lib/python3.7/multiprocessing/pool.py", line 354, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/usr/local/anaconda3/envs/myenv/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
AttributeError: 'Attribute' object has no attribute 'id'
```

It seems that changing the checker for DJ03 from

```
class RenderChecker(Checker):

    def run(self, node):
        """
        Captures the use of locals() in render function.
        """
        if self.get_call_name(node) != 'render':
            return
        issues = []
        for arg in node.args:
            if isinstance(arg, ast.Call) and arg.func.id == 'locals':
                issues.append(
                    DJ03(
                        lineno=node.lineno,
                        col=node.col_offset,
                    )
                )
        return issues
```

to 

```
class RenderChecker(Checker):

    def run(self, node):
        """
        Captures the use of locals() in render function.
        """
        if self.get_call_name(node) != 'render':
            return
        issues = []
        for arg in node.args:
            if isinstance(arg, ast.Call) and getattr(arg.func, 'id', '') == 'locals':
                issues.append(
                    DJ03(
                        lineno=node.lineno,
                        col=node.col_offset,
                    )
                )
        return issues
```

Completely takes care of the issue.

**Comment by GitRon** [comment]
Same for me.

**Comment by GitRon** [comment]
@jon-mcclung-fortyau I put your idea with a second fix in a new PR
