### ISSUE TITLE
AttributeError: 'UnaryOp' object has no attribute 'value'

### ISSUE THREAD

**Issue by nijel** [rocioar/flake8-django#74]
When running flake8-django 1.10 on [Weblate](https://github.com/WeblateOrg/weblate/) it crashes:

```pytb
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/flake8/checker.py", line 655, in _run_checks
    return checker.run_checks()
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/flake8/checker.py", line 589, in run_checks
    self.run_ast_checks()
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/flake8/checker.py", line 496, in run_ast_checks
    for (line_number, offset, text, _) in runner:
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/flake8_django/checker.py", line 62, in run
    parser.visit(self.tree)
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/ast.py", line 371, in generic_visit
    self.visit(item)
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/flake8_django/checker.py", line 45, in visit_ClassDef
    self.capture_issues_visitor('ClassDef', node)
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/flake8_django/checker.py", line 39, in capture_issues_visitor
    self.generic_visit(node)
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/ast.py", line 371, in generic_visit
    self.visit(item)
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/ast.py", line 373, in generic_visit
    self.visit(value)
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/flake8_django/checker.py", line 42, in visit_Call
    self.capture_issues_visitor('Call', node)
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/flake8_django/checker.py", line 36, in capture_issues_visitor
    issues = checker.run(node)
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/flake8_django/checkers/model_fields.py", line 35, in run
    if keyword.arg == 'blank' and keyword.value.value is True:
AttributeError: 'UnaryOp' object has no attribute 'value'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.3/x64/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/flake8/main/application.py", line 360, in run
    self._run(argv)
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/flake8/main/application.py", line 348, in _run
    self.run_checks()
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/flake8/main/application.py", line 262, in run_checks
    self.file_checker_manager.run()
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/flake8/checker.py", line 323, in run
    self.run_parallel()
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/flake8/checker.py", line 289, in run_parallel
    for ret in pool_map:
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/multiprocessing/pool.py", line 448, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
AttributeError: 'UnaryOp' object has no attribute 'value'
```

The CI job with full log is here: https://github.com/WeblateOrg/weblate/runs/704322639

**Comment by rocioar** [comment]
@nijel I released a new version with a fix: 1.1.1, sorry for the troubles.
